DROP TABLE IF EXISTS Product;

CREATE TABLE Product(
    ID SERIAL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    QUANTITY INT NOT NULL,
    PRICE NUMERIC(8,2) NOT NULL,
    TIME_CREATED TIMESTAMP DEFAULT NOW()
);

INSERT INTO Product( ID, NAME, DESCRIPTION, QUANTITY, PRICE) VALUES (1, 'P1', '', 1, 200.00), (2, 'P2', '', 3, 400.00);

DROP TABLE IF EXISTS Tax;
CREATE TABLE Tax(
    ID SERIAL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    RATE NUMERIC(8,2) NOT NULL,
    TIME_CREATED TIMESTAMP DEFAULT NOW()
);
INSERT INTO Tax( ID, NAME, DESCRIPTION, RATE) VALUES (1, 'VAT', '', 10.00);

DROP TABLE IF EXISTS Sale;
CREATE TABLE Sale(
    ID SERIAL,
    TOTAL_AMOUNT NUMERIC(8,2) NOT NULL,
    TOTAL_TAX NUMERIC(8,2) NOT NULL,
    SALES_AMOUNT NUMERIC(8,2) NOT NULL,
    TIME_CREATED TIMESTAMP DEFAULT NOW()
);
INSERT INTO Sale( ID, TOTAL_AMOUNT, TOTAL_TAX, SALES_AMOUNT) VALUES (1, 200.00, 20.00, 180.00);

DROP TABLE IF EXISTS ProductSales;
CREATE TABLE ProductSales(
    ID SERIAL,
    SALE_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    SALE_QUANTITY INTEGER,
    SALE_PRICE NUMERIC(8,2),
    FOREIGN KEY (SALE_ID) REFERENCES Sale(id) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES Product(id) ON DELETE CASCADE
);
INSERT INTO ProductSales( ID, SALE_ID, PRODUCT_ID, SALE_QUANTITY, SALE_PRICE) VALUES (1, 1, 1, 1,  200.00);
